vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - oderwat.indent-rainbow
    - Prisma.prisma
    - sleistner.vscode-fileutils
