/* eslint-disable */
import '@prisma/client'
import '@remix-run/express'
import '@remix-run/node'
import '@remix-run/react'
import '@remix-run/server-runtime'
import 'bcryptjs'
import 'compression'
import 'cross-env'
import 'dotenv'
import 'express'
import 'express-prometheus-middleware'
import 'isbot'
import 'morgan'
import 'prom-client'
import 'react'
import 'react-dom'
import 'tiny-invariant'
